import type { Card, Color } from "@/domain/cards/types";

type FixtureCardInput = Omit<Card, "id" | "oracleId" | "normalizedName" | "legalities" | "prices" | "purchaseUris" | "imageUrl"> & {
  usd: number | null;
  producedMana?: Color[];
};

const normalizeName = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const purchaseName = (name: string) => encodeURIComponent(name);

const createFixtureCard = (input: FixtureCardInput): Card => ({
  id: `fixture-${normalizeName(input.name)}`,
  oracleId: `fixture-oracle-${normalizeName(input.name)}`,
  name: input.name,
  normalizedName: normalizeName(input.name),
  manaCost: input.manaCost,
  manaValue: input.manaValue,
  colorIdentity: input.colorIdentity,
  typeLine: input.typeLine,
  oracleText: input.oracleText,
  legalities: { commander: "legal" },
  edhrecRank: input.edhrecRank,
  gameChanger: input.gameChanger,
  prices: { usd: input.usd, eur: null, tix: null },
  purchaseUris: {
    tcgplayer: `https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=${purchaseName(input.name)}`,
    cardmarket: `https://www.cardmarket.com/en/Magic/Products/Search?searchString=${purchaseName(input.name)}`,
    cardhoarder: `https://www.cardhoarder.com/cards?data%5Bsearch%5D=${purchaseName(input.name)}`,
  },
  imageUrl: `https://cards.scryfall.io/normal/front/${normalizeName(input.name)}.jpg`,
  ...(input.producedMana ? { producedMana: input.producedMana } : {}),
});

export const fixtureCards: Card[] = [
  createFixtureCard({
    name: "Alela, Artful Provocateur",
    manaCost: "{1}{W}{U}{B}",
    manaValue: 4,
    colorIdentity: ["W", "U", "B"],
    typeLine: "Legendary Creature - Faerie Warlock",
    oracleText: "Flying, deathtouch, lifelink. Other creatures you control with flying get +1/+0. Whenever you cast an artifact or enchantment spell, create a 1/1 blue Faerie creature token with flying.",
    edhrecRank: 4780,
    gameChanger: false,
    usd: 0.75,
  }),
  createFixtureCard({
    name: "Sol Ring",
    manaCost: "{1}",
    manaValue: 1,
    colorIdentity: [],
    typeLine: "Artifact",
    oracleText: "{T}: Add {C}{C}.",
    edhrecRank: 1,
    gameChanger: true,
    usd: 1.35,
  }),
  createFixtureCard({
    name: "Arcane Signet",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: [],
    typeLine: "Artifact",
    oracleText: "{T}: Add one mana of any color in your commander's color identity.",
    edhrecRank: 2,
    gameChanger: false,
    usd: 0.45,
    producedMana: ["W", "U", "B"],
  }),
  createFixtureCard({
    name: "Command Tower",
    manaCost: "",
    manaValue: 0,
    colorIdentity: [],
    typeLine: "Land",
    oracleText: "{T}: Add one mana of any color in your commander's color identity.",
    edhrecRank: 3,
    gameChanger: false,
    usd: 0.25,
    producedMana: ["W", "U", "B"],
  }),
  createFixtureCard({
    name: "Swords to Plowshares",
    manaCost: "{W}",
    manaValue: 1,
    colorIdentity: ["W"],
    typeLine: "Instant",
    oracleText: "Exile target creature. Its controller gains life equal to its power.",
    edhrecRank: 18,
    gameChanger: false,
    usd: 1.1,
  }),
  createFixtureCard({
    name: "Counterspell",
    manaCost: "{U}{U}",
    manaValue: 2,
    colorIdentity: ["U"],
    typeLine: "Instant",
    oracleText: "Counter target spell.",
    edhrecRank: 64,
    gameChanger: false,
    usd: 1.4,
  }),
  createFixtureCard({
    name: "Phyrexian Arena",
    manaCost: "{1}{B}{B}",
    manaValue: 3,
    colorIdentity: ["B"],
    typeLine: "Enchantment",
    oracleText: "At the beginning of your upkeep, you draw a card and you lose 1 life.",
    edhrecRank: 175,
    gameChanger: false,
    usd: 2.5,
  }),
  createFixtureCard({
    name: "Bitterblossom",
    manaCost: "{1}{B}",
    manaValue: 2,
    colorIdentity: ["B"],
    typeLine: "Tribal Enchantment - Faerie",
    oracleText: "At the beginning of your upkeep, you lose 1 life and create a 1/1 black Faerie Rogue creature token with flying.",
    edhrecRank: 2700,
    gameChanger: false,
    usd: 20,
  }),
  createFixtureCard({
    name: "Island",
    manaCost: "",
    manaValue: 0,
    colorIdentity: [],
    typeLine: "Basic Land - Island",
    oracleText: "({T}: Add {U}.)",
    edhrecRank: null,
    gameChanger: false,
    usd: 0.05,
    producedMana: ["U"],
  }),
  createFixtureCard({
    name: "Plains",
    manaCost: "",
    manaValue: 0,
    colorIdentity: [],
    typeLine: "Basic Land - Plains",
    oracleText: "({T}: Add {W}.)",
    edhrecRank: null,
    gameChanger: false,
    usd: 0.05,
    producedMana: ["W"],
  }),
  createFixtureCard({
    name: "Swamp",
    manaCost: "",
    manaValue: 0,
    colorIdentity: [],
    typeLine: "Basic Land - Swamp",
    oracleText: "({T}: Add {B}.)",
    edhrecRank: null,
    gameChanger: false,
    usd: 0.05,
    producedMana: ["B"],
  }),
  createFixtureCard({
    name: "Azorius Signet",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: ["W", "U"],
    typeLine: "Artifact",
    oracleText: "{1}, {T}: Add {W}{U}.",
    edhrecRank: 310,
    gameChanger: false,
    usd: 0.45,
    producedMana: ["W", "U"],
  }),
  createFixtureCard({
    name: "Orzhov Signet",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: ["W", "B"],
    typeLine: "Artifact",
    oracleText: "{1}, {T}: Add {W}{B}.",
    edhrecRank: 325,
    gameChanger: false,
    usd: 0.4,
    producedMana: ["W", "B"],
  }),
  createFixtureCard({
    name: "Dimir Signet",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: ["U", "B"],
    typeLine: "Artifact",
    oracleText: "{1}, {T}: Add {U}{B}.",
    edhrecRank: 305,
    gameChanger: false,
    usd: 0.5,
    producedMana: ["U", "B"],
  }),
  createFixtureCard({
    name: "Path to Exile",
    manaCost: "{W}",
    manaValue: 1,
    colorIdentity: ["W"],
    typeLine: "Instant",
    oracleText: "Exile target creature. Its controller may search their library for a basic land card, put that card onto the battlefield tapped, then shuffle.",
    edhrecRank: 85,
    gameChanger: false,
    usd: 1.25,
  }),
  createFixtureCard({
    name: "Damn",
    manaCost: "{B}{B}",
    manaValue: 2,
    colorIdentity: ["W", "B"],
    typeLine: "Sorcery",
    oracleText: "Destroy target creature. A creature destroyed this way can't be regenerated. Overload {2}{W}{W}.",
    edhrecRank: 2200,
    gameChanger: false,
    usd: 4.5,
  }),
  createFixtureCard({
    name: "Reconnaissance Mission",
    manaCost: "{2}{U}{U}",
    manaValue: 4,
    colorIdentity: ["U"],
    typeLine: "Enchantment",
    oracleText: "Whenever a creature you control deals combat damage to a player, you may draw a card. Cycling {2}.",
    edhrecRank: 1500,
    gameChanger: false,
    usd: 0.25,
  }),
  createFixtureCard({
    name: "Favorable Winds",
    manaCost: "{1}{U}",
    manaValue: 2,
    colorIdentity: ["U"],
    typeLine: "Enchantment",
    oracleText: "Creatures you control with flying get +1/+1.",
    edhrecRank: 3900,
    gameChanger: false,
    usd: 0.2,
  }),
  createFixtureCard({
    name: "Anointed Procession",
    manaCost: "{3}{W}",
    manaValue: 4,
    colorIdentity: ["W"],
    typeLine: "Enchantment",
    oracleText: "If an effect would create one or more tokens under your control, it creates twice that many of those tokens instead.",
    edhrecRank: 240,
    gameChanger: false,
    usd: 42,
  }),
  createFixtureCard({
    name: "Watery Grave",
    manaCost: "",
    manaValue: 0,
    colorIdentity: ["U", "B"],
    typeLine: "Land - Island Swamp",
    oracleText: "As this land enters, you may pay 2 life. If you don't, it enters tapped.",
    edhrecRank: 215,
    gameChanger: false,
    usd: 12,
    producedMana: ["U", "B"],
  }),
  createFixtureCard({
    name: "Godless Shrine",
    manaCost: "",
    manaValue: 0,
    colorIdentity: ["W", "B"],
    typeLine: "Land - Plains Swamp",
    oracleText: "As this land enters, you may pay 2 life. If you don't, it enters tapped.",
    edhrecRank: 230,
    gameChanger: false,
    usd: 11,
    producedMana: ["W", "B"],
  }),
  createFixtureCard({
    name: "Hallowed Fountain",
    manaCost: "",
    manaValue: 0,
    colorIdentity: ["W", "U"],
    typeLine: "Land - Plains Island",
    oracleText: "As this land enters, you may pay 2 life. If you don't, it enters tapped.",
    edhrecRank: 225,
    gameChanger: false,
    usd: 10,
    producedMana: ["W", "U"],
  }),
  createFixtureCard({
    name: "Talisman of Dominance",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: ["U", "B"],
    typeLine: "Artifact",
    oracleText: "{T}: Add {C}. {T}: Add {U} or {B}. This artifact deals 1 damage to you.",
    edhrecRank: 360,
    gameChanger: false,
    usd: 1.2,
    producedMana: ["U", "B"],
  }),
  createFixtureCard({
    name: "Talisman of Progress",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: ["W", "U"],
    typeLine: "Artifact",
    oracleText: "{T}: Add {C}. {T}: Add {W} or {U}. This artifact deals 1 damage to you.",
    edhrecRank: 355,
    gameChanger: false,
    usd: 1.1,
    producedMana: ["W", "U"],
  }),
  createFixtureCard({
    name: "Talisman of Hierarchy",
    manaCost: "{2}",
    manaValue: 2,
    colorIdentity: ["W", "B"],
    typeLine: "Artifact",
    oracleText: "{T}: Add {C}. {T}: Add {W} or {B}. This artifact deals 1 damage to you.",
    edhrecRank: 365,
    gameChanger: false,
    usd: 1.15,
    producedMana: ["W", "B"],
  }),
  createFixtureCard({
    name: "Skullclamp",
    manaCost: "{1}",
    manaValue: 1,
    colorIdentity: [],
    typeLine: "Artifact - Equipment",
    oracleText: "Equipped creature gets +1/-1. Whenever equipped creature dies, draw two cards. Equip {1}.",
    edhrecRank: 45,
    gameChanger: true,
    usd: 4,
  }),
  createFixtureCard({
    name: "Smothering Tithe",
    manaCost: "{3}{W}",
    manaValue: 4,
    colorIdentity: ["W"],
    typeLine: "Enchantment",
    oracleText: "Whenever an opponent draws a card, that player may pay {2}. If the player doesn't, you create a Treasure token.",
    edhrecRank: 28,
    gameChanger: true,
    usd: 32,
  }),
  createFixtureCard({
    name: "Kindred Discovery",
    manaCost: "{3}{U}{U}",
    manaValue: 5,
    colorIdentity: ["U"],
    typeLine: "Enchantment",
    oracleText: "As this enchantment enters, choose a creature type. Whenever a creature you control of the chosen type enters or attacks, draw a card.",
    edhrecRank: 950,
    gameChanger: false,
    usd: 8,
  }),
  createFixtureCard({
    name: "Faerie Seer",
    manaCost: "{U}",
    manaValue: 1,
    colorIdentity: ["U"],
    typeLine: "Creature - Faerie Wizard",
    oracleText: "Flying. When this creature enters, scry 2.",
    edhrecRank: 7200,
    gameChanger: false,
    usd: 0.12,
  }),
  createFixtureCard({
    name: "Oona's Blackguard",
    manaCost: "{1}{B}",
    manaValue: 2,
    colorIdentity: ["B"],
    typeLine: "Creature - Faerie Rogue",
    oracleText: "Flying. Each other Rogue creature you control enters with an additional +1/+1 counter on it. Whenever a creature you control with a +1/+1 counter deals combat damage to a player, that player discards a card.",
    edhrecRank: 6500,
    gameChanger: false,
    usd: 0.35,
  }),
  createFixtureCard({
    name: "Tegwyll, Duke of Splendor",
    manaCost: "{1}{U}{B}",
    manaValue: 3,
    colorIdentity: ["U", "B"],
    typeLine: "Legendary Creature - Faerie Noble",
    oracleText: "Flying, deathtouch. Other Faeries you control get +1/+1. Whenever another Faerie you control dies, you draw a card and you lose 1 life.",
    edhrecRank: 5200,
    gameChanger: false,
    usd: 0.4,
  }),
];

const fixturesByName = new Map(fixtureCards.map((card) => [card.normalizedName, card]));

export function fixtureCard(name: string): Card {
  const card = fixturesByName.get(normalizeName(name));
  if (!card) throw new Error(`Unknown fixture card: ${name}`);
  return { ...card, colorIdentity: [...card.colorIdentity], producedMana: card.producedMana ? [...card.producedMana] : undefined };
}
